# Generated by Django 5.2.4 on 2025-07-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heat_treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('cast_code', models.CharField(max_length=100)),
                ('heat_code', models.CharField(max_length=100)),
                ('determination', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Rework', 'Rework'), ('Scrap', 'Scrap')], max_length=20)),
                ('defects', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dim_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_7', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_8', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_9', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dim_10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heat_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to='heat_treatment.heattreatmentbatch')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
