# Generated by Django 5.2.4 on 2025-07-17 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatTreatmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_code', models.CharField(max_length=20)),
                ('heat_code', models.CharField(max_length=20)),
                ('hard_shell', models.PositiveIntegerField()),
                ('soft_shell', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('released_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_treatment_records', to='product.product')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
