# Generated by Django 5.2.4 on 2025-07-23 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('cast_code', models.CharField(max_length=50)),
                ('heat_code', models.CharField(max_length=50)),
                ('hardness_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='heat_treatment.heattreatmentbatch')),
            ],
        ),
    ]
