# Generated by Django 5.2.4 on 2025-07-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateofconformance',
            name='final_inspection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateofconformance',
            name='heat_treatment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateofconformance',
            name='mpi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateofconformance',
            name='ut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CofCComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('cast_code', models.CharField(max_length=50)),
                ('heat_code', models.CharField(max_length=50)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='certificate.certificateofconformance')),
            ],
        ),
    ]
