# Generated by Django 5.2.4 on 2025-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificateofconformance_final_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateofconformance',
            name='order',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
