# Generated by Django 5.2.4 on 2025-07-17 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasonicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('cast_code', models.CharField(max_length=50)),
                ('heat_code', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('sentence', models.CharField(choices=[('Pass', 'Pass'), ('Rework', 'Rework'), ('Scrap', 'Scrap')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultrasonic_tests_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
