# Generated by Django 5.2.4 on 2025-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonictest',
            name='operation_type',
            field=models.CharField(choices=[('UT', 'UT'), ('MPI', 'MPI')], max_length=10, null=True),
        ),
    ]
