# Generated by Django 5.2.4 on 2025-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic', '0002_ultrasonictest_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasonictest',
            name='serial',
            field=models.CharField(max_length=50),
        ),
    ]
