# Generated by Django 5.2.4 on 2025-07-17 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heat_treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('cast_code', models.CharField(max_length=100)),
                ('heat_code', models.CharField(max_length=100)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banding_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('heat_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banding_records', to='heat_treatment.heattreatmentbatch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
