# Generated by Django 5.2.4 on 2025-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='diameter',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='banding',
            name='gap',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='banding',
            name='pressure',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
