# Generated by Django 5.2.4 on 2025-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banding', '0002_alter_banding_diameter_alter_banding_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='diameter',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='banding',
            name='gap',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='banding',
            name='pressure',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
