# Generated by Django 5.2.4 on 2025-07-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heat_treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCMachiningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_desc', models.CharField(max_length=100)),
                ('op_no', models.CharField(max_length=50)),
                ('machine_no', models.CharField(max_length=50)),
                ('determination', models.CharField(choices=[('Pass', 'Pass'), ('Rework', 'Rework'), ('Scrap', 'Scrap')], max_length=20)),
                ('comments', models.TextField(blank=True, default='-')),
                ('shift', models.CharField(max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('heat_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_records', to='heat_treatment.heattreatmentbatch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
