# Generated by Django 5.2.4 on 2025-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_machining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operation_number', models.IntegerField()),
            ],
        ),
    ]
