# Generated by Django 5.2.4 on 2025-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_machining', '0002_cncoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cncmachiningrecord',
            name='op_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
